version: '3'
services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: 'root'
    ports:
      - '5432:5432'
  api:
    build: .
    volumes:
      - ./:/app
    ports:
      - '3000:3000'
    command: 'sh -c "yarn && yarn start:dev"'
    depends_on:
      - db
