GET http://localhost:3000/partners/2/users?conditions=%7B%7D&skip=0&limit=25&sort=%7B%22updatedAt%22:-1%7D
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsInVzZXJuYW1lIjoiam9zZWx1Y2FzY2hvY2lhaStwYXJjZWlyb0BnbWFpbC5jb20iLCJ1c2VyVHlwZSI6InBhcnRuZXIiLCJwYXJ0bmVySWQiOjEsImlhdCI6MTcwMTEzODA2MCwiZXhwIjoxNzAxMTQxNjYwfQ.NDWU2OYHEv3n62rguQzemmm0ksCvgNEd4pctLZ5ZwMo

###

GET http://localhost:3000/products/categories/1/sizes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsInVzZXJuYW1lIjoiam9zZWx1Y2FzY2hvY2lhaStwYXJjZWlyb0BnbWFpbC5jb20iLCJ1c2VyVHlwZSI6InBhcnRuZXIiLCJwYXJ0bmVySWQiOjEsImlhdCI6MTcwMTEzODA2MCwiZXhwIjoxNzAxMTQxNjYwfQ.NDWU2OYHEv3n62rguQzemmm0ksCvgNEd4pctLZ5ZwMo###

###

GET http://localhost:3000/customers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsInVzZXJuYW1lIjoiam9zZWx1Y2FzY2hvY2lhaStwYXJjZWlyb0BnbWFpbC5jb20iLCJ1c2VyVHlwZSI6InBhcnRuZXIiLCJwYXJ0bmVySWQiOjEsImlhdCI6MTcwMTEzODA2MCwiZXhwIjoxNzAxMTQxNjYwfQ.NDWU2OYHEv3n62rguQzemmm0ksCvgNEd4pctLZ5ZwMo
